(depends-on "android-mode")

(depends-on "auctex-latexmk")

(depends-on "browse-kill-ring")

(depends-on "company-auctex")
(depends-on "company-ess")

(depends-on "evil")
(depends-on "evil-exchange")
(depends-on "evil-indent-textobject")
(depends-on "evil-jumper")
(depends-on "evil-leader")
(depends-on "evil-matchit")
(depends-on "evil-nerd-commenter")
(depends-on "evil-numbers")
(depends-on "evil-org")
(depends-on "evil-smartparens")
(depends-on "evil-surround")
(depends-on "evil-tutor")
(depends-on "evil-visualstar")

(depends-on "f")

(depends-on "flycheck-tip")

(depends-on "iedit")

(depends-on "json-mode")
(depends-on "json-reformat")

(depends-on "markdown-mode+")

(depends-on "ox-pandoc")
(depends-on "package-build")

(depends-on "powerline")

(depends-on "py-autopep8")

(depends-on "s")
(depends-on "shut-up")

(depends-on "stripe-buffer")
