;;; -*- coding: utf-8 -*-
(("/Users/rubens/Copy/docs/livros.txt" . 7893)
 ("/Users/rubens/Copy/docs/Cameras_comparisson.txt" . 1391)
 ("/Users/rubens/Downloads/conkerorrc" . 3704)
 ("/Users/rubens/Projects/git/dotfiles/emacs.d/emacs-init.org" . 4250)
 ("/Users/rubens/Projects/git/dotfiles/emacs.d/init.el" . 490)
 ("/Users/rubens/.emacs.d/recentf" . 514)
 ("/Users/rubens/Projects/git/dotfiles/conkerorrc" . 26)
 ("/Users/rubens/Downloads/research-toolkit.org" . 2752)
 ("/Users/rubens/.emacs.d/elpa/company-20150309.1835/company-autoloads.el" . 8123)
 ("/Users/rubens/.emacs.d/elpa/concurrent-20150309.2052/concurrent-autoloads.el" . 229)
 ("/Users/rubens/.emacs.d/elpa/deferred-20150309.2052/deferred-autoloads.el" . 225)
 ("/Users/rubens/.emacs.d/elpa/helm-20150309.2222/helm-autoloads.el" . 35865)
 ("/Users/rubens/.emacs.d/elpa/julia-mode-20150309.1220/julia-mode-autoloads.el" . 538)
 ("/Users/rubens/.emacs.d/elpa/python-environment-20150310.153/python-environment-autoloads.el" . 310)
 ("/Users/rubens/Projects/git/6.00.1x/6001x-notes.org" . 16745)
 ("/Users/rubens/Copy/Org/www.org" . 2489)
 ("/Users/rubens/.mail/.notmuch/hooks/post-new" . 189)
 ("/Users/rubens/.notmuch-config" . 2576)
 ("/Users/rubens/.emacs.d/elfeed.org" . 7)
 ("/Users/rubens/.mbsyncrc" . 993)
 ("/Users/rubens/Projects/classes/"
  (dired-filename . "/Users/rubens/Projects/classes/.DS_Store"))
 ("/Users/rubens/.elfeed/index" . 981452)
 ("/Users/rubens/Projects/classes/Learn_Python_The_Hard_Way.org" . 8566)
 ("/Users/rubens/Projects/classes/Learn_Python_The_Hard_Way.py" . 798)
 ("/Users/rubens/Projects/git/dotfiles/zshrc" . 3445)
 ("/Users/rubens/Projects/git/6.00.1x/test.py" . 1420)
 ("/Users/rubens/Projects/classes/Learn_Python_The_Hard_Way.html" . 6424)
 ("/Users/rubens/Copy/Org/notes.org" . 47591)
 ("/Users/rubens/Projects/git/dotfiles/mbsyncrc" . 1033)
 ("/Users/rubens/.gnupg/gpg.conf" . 9164)
 ("/Users/rubens/.cert/imap.gmail.com.pem" . 1605)
 ("/Users/rubens/.cert/Equifax_Secure_CA.pem" . 1268)
 ("/Users/rubens/Projects/git/dotfiles/emacs.d/Cask" . 39)
 ("/Users/rubens/Projects/git/dotfiles/emacs.d/settings.org" . 1649)
 ("/Users/rubens/Projects/git/dotfiles/emacs.d/.gitignore" . 98)
 ("/Users/rubens/.Rprofile" . 210)
 ("/Users/rubens/Projects/git/6.00.1x/code_ProblemSet6/ps6_encryption_my_solution.py" . 4921)
 ("/Users/rubens/Projects/git/notebooks/"
  (dired-filename . "/Users/rubens/Projects/git/notebooks/MITx-6.00.1x-Introduction to Computer Science and Programming Using Python.ipynb"))
 ("/Users/rubens/Projects/classes/ScyPython/notes.org" . 230)
 ("/Users/rubens/Downloads/"
  (dired-filename . "/Users/rubens/Downloads/essential-packages-howtotex.tex"))
 ("/Users/rubens/Projects/git/6.00.1x/my_scripts/semordnilap.py" . 528)
 ("/Users/rubens/Projects/git/6.00.1x/my_scripts/oddTuples.py" . 46)
 ("/Users/rubens/Projects/git/6.00.1x/my_scripts/isIn.py" . 528)
 ("/Users/rubens/Projects/git/6.00.1x/my_scripts/lists.py" . 510)
 ("/Users/rubens/Projects/git/6.00.1x/my_scripts/dictionaries.py" . 1051)
 ("/Users/rubens/Projects/git/6.00.1x/my_scripts/gcdRecur.py" . 211)
 ("/Users/rubens/Projects/git/6.00.1x/my_scripts/lenRecur.py" . 124)
 ("/Users/rubens/Projects/git/6.00.1x/my_scripts/recurPowerNew.py" . 332)
 ("/Users/rubens/Projects/git/6.00.1x/l3_q9-bisection_problem.py" . 721)
 ("/Users/rubens/Projects/git/6.00.1x/lectureCode_lec3.6.2.py" . 71)
 ("/Users/rubens/Copy/"
  (dired-filename . "/Users/rubens/Copy/Org"))
 ("/Users/rubens/Copy/Org/"
  (dired-filename . "/Users/rubens/Copy/Org/notes.org"))
 ("/Users/rubens/Projects/git/6.00.1x/lectureCode_lec3.3.3.py" . 105)
 ("/Users/rubens/Projects/git/6.00.1x/lectureCode_Lec2.5.4.py" . 13)
 ("/Users/rubens/Projects/git/6.00.1x/lectureCode_Lec2.6.4.py" . 270)
 ("/Users/rubens/Projects/git/6.00.1x/"
  (dired-filename . "/Users/rubens/Projects/git/6.00.1x/pset0Test.py"))
 ("/Users/rubens/.emacs.d/"
  (dired-filename . "/Users/rubens/.emacs.d/emacs-init.org"))
 ("/Users/rubens/Projects/"
  (dired-filename . "/Users/rubens/Projects/git"))
 ("/Users/rubens/Projects/git/"
  (dired-filename . "/Users/rubens/Projects/git/karel-the-robot-learns-java"))
 ("/Users/rubens/Copy/Org/moocs.org" . 500)
 ("/Users/rubens/"
  (dired-filename . "/Users/rubens/.CFUserTextEncoding"))
 ("/Users/rubens/Copy/Org/ideas.org" . 459)
 ("/Users/rubens/Projects/git/dotfiles/emacs.d/backups/"
  (dired-filename . "/Users/rubens/Projects/git/dotfiles/emacs.d/backups/.."))
 ("/Users/rubens/Projects/git/dotfiles/emacs.d/"
  (dired-filename . "/Users/rubens/Projects/git/dotfiles/emacs.d/emacs-init.org"))
 ("/Users/rubens/Projects/git/dotfiles/"
  (dired-filename . "/Users/rubens/Projects/git/dotfiles/emacs.d")))
