---
- name: 'Archlinux installation'
  hosts: localhost
  become: yes

  tasks:
    - name: Update package repositories
      pacman:
        update_cache: yes
        upgrade: yes
      tags:
        - update

    - name: Install universal base packages
      pacman:
        name: {{ item }}
        state: present
        update_cache: yes
      with_items:
        - vim
        - emacs
        - zsh
        - rxvt-unicode
        - keychain
        - fortune-mod
        - tmux
        - glances
        - xorg-x11
        - xf86-input-evdev
        - i3
        - xrandr
        - dmenu
        - numlockx
        - xscreensaver
        - feh
        - thunar
        - p7zip
        - unrar
        - unzip
        - file-roller
        - firefox
        - texlive
        - pandoc
        - pavucontrol
        - evince
        - mupdf
        - mcomix
        - mpv
      tags:
        - install
