---
- name: 'Funtoo installation'
  hosts: localhost
  become: yes

  tasks:
    - name: Update package repositories
      portage: sync=yes
      tags:
        - update

    - name: Install universal base packages
      portage: package={{ item }} state=present
      with_items:
        - gentoolkit
        - vim
        - emacs
        - zsh
        - tmux
        - glances
        - eix
        - xorg-x11
        - xf86-input-evdev
        - i3
        - i3status
        - xrandr
        - dmenu
        - numlockx
        - xscreensaver
        - feh
        - thunar
        - p7zip
        - unrar
        - unzip
        - file-roller
        - firefox
      tags:
        - packages
